name: crafted_well_mobile_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # State Management 
  provider: ^6.1.1
  
  # Data Integration 
  http: ^1.1.0                    # External JSON files & MySQL API calls
  sqflite: ^2.3.0                 # Local database read/write
  path_provider: ^2.1.1           # File system access for local storage
  
  # Mobile Device Capabilities
  geolocator: ^10.1.0             # GPS location
  connectivity_plus: ^5.0.2       # Network connectivity monitoring  
  camera: ^0.10.5+5               # Camera access
  battery_plus: ^5.0.2            # Battery status
  permission_handler: ^11.1.0     # Handle device permissions
  path: ^1.8.3
  image_picker: ^1.0.4

  
  # Optional: Enhanced Authentication
  shared_preferences: ^2.2.2      # Simple local storage for user sessions

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Crafted Well Logo (2).png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/Crafted Well Logo (2).png
    - assets/images/Dark Glass Bottle Mocha 1.png
    - assets/images/city.png
    - assets/images/tropical.png
    - assets/images/moderate.png
    - assets/images/product-image-1.png
    - assets/images/product-image-2.png
    - assets/images/product-image-3.png
    - assets/images/product-image-4.png
    # Added JSON files for offline data requirement
    - assets/data/products.json
    - assets/data/offline_data.json

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic